#!/bin/bash
# Helper script to get correct Supabase connection string

echo "🔍 Getting Supabase Connection String"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/gjwzaylkzknsykjvtpcd"
echo "2. Navigate to: Settings → Database"
echo "3. Scroll to 'Connection string' section"
echo ""
echo "For Session Pooler (Recommended):"
echo "  - Click 'Connection Pooling' tab"
echo "  - Select 'Session pooler'"
echo "  - Copy the connection string"
echo "  - Replace [YOUR-PASSWORD] with: Mridulahemant1*"
echo ""
echo "For Direct Connection:"
echo "  - Click 'URI' tab"
echo "  - Copy the connection string"
echo "  - Replace [YOUR-PASSWORD] with: Mridulahemant1*"
echo ""
echo "Then update backend/.env file:"
echo "  SUPABASE_DB_URL=<paste-connection-string-here>"
echo ""
echo "After updating, test with:"
echo "  python3 backend/test_db_connection.py"

